require("jonas.plugins.mini")
-- require("jonas.plugins.leap")
-- require("jonas.plugins.snap") -- TODO: flake
require("jonas.plugins.noice")
-- require("jonas.plugins.treesj") -- TODO: reconsider keymaps
require("jonas.plugins.snacks")
require("jonas.plugins.incline")
require("jonas.plugins.conform")
require("jonas.plugins.gitsigns")
require("jonas.plugins.markview")
require("jonas.plugins.nvim-lint")
require("jonas.plugins.blink-pairs")
require("jonas.plugins.live-preview")
require("jonas.plugins.nvim-colorizer")
require("jonas.plugins.nvim-treesitter")
